// src/components/article-card.tsx
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { cn } from '@/lib/utils'
import { articlesAtom } from '@/store'
import { BUTTON_LIST } from '@/store/const'
import type { ArticleType } from '@/types'
import { useAtom } from 'jotai'

const ArticleCard = ({ index }: { index: number }) => {
  const [articles, setArticles] = useAtom(articlesAtom)
  const handleUpdateArticle = (updatedField: Partial<ArticleType>) => {
    setArticles((prevArticles) => {
      return [
        ...prevArticles.slice(0, index),
        { ...prevArticles[index], ...updatedField },
        ...prevArticles.slice(index + 1),
      ]
    })
  }

  const article = articles[index]

  return (
    <div
      className={cn(
        'flex flex-col items-start gap-2 rounded-lg border p-3',
        article.include ? 'bg-accent/80' : 'bg-transparent',
      )}
    >
      <div className="w-full flex-1 flex flex-col gap-4">
        <div className="w-full flex justify-between gap-2">
          <a
            href={article.url}
            target="_blank"
            rel="noreferrer"
            className="text-base font-semibold tracking-wider hover:underline underline-offset-4 break-keep"
          >
            {article.title}
          </a>
          <Checkbox
            checked={article.include}
            onClick={() => handleUpdateArticle({ include: !article.include })}
            className="rounded-full w-6 h-6"
          />
        </div>
        <div className="flex justify-between">
          <RadioGroup className="flex flex-wrap gap-2">
            {BUTTON_LIST.map((button, bi) => {
              return (
                <label key={bi} htmlFor={button.value}>
                  <RadioGroupItem
                    value={button.value}
                    id={button.value}
                    className="hidden"
                  />
                  <Button
                    variant={'outline'}
                    size={'sm'}
                    className={cn(
                      'text-xs h-7',
                      article.type === button.value &&
                        'bg-primary text-primary-foreground hover:bg-primary/90',
                    )}
                    onClick={() => handleUpdateArticle({ type: button.value })}
                  >
                    {button.label}
                  </Button>
                </label>
              )
            })}
          </RadioGroup>
          <Button
            variant={'reference'}
            size={'sm'}
            className={cn(
              'text-xs h-7',
              article.typeRef &&
                'bg-blue-500 text-primary-foreground hover:bg-blue-500/80',
            )}
            onClick={() => handleUpdateArticle({ typeRef: !article.typeRef })}
          >
            참고
          </Button>
        </div>
      </div>
      <div className="flex gap-4">
        <Input
          type="text"
          placeholder="키워드1"
          value={article.keyword1}
          onChange={(e) => handleUpdateArticle({ keyword1: e.target.value })}
          autoComplete="on"
          className="h-8 px-0"
        />
        <Input
          type="text"
          placeholder="키워드2"
          value={article.keyword2}
          onChange={(e) => handleUpdateArticle({ keyword2: e.target.value })}
          autoComplete="on"
          className="h-8 px-0"
        />
      </div>
    </div>
  )
}

export default ArticleCard

// frontend/src/components/article-card.svelte
<script>
	import { NEWS_TYPE } from '../utils/const'

	export let date;
	export let title;
	export let url;
	export let category;
	export let type
	export let typeRef
	export let keyword1
	export let keyword2
</script>

<div class="container">
	<div class="header">
		<sub>{date}{category ? ` · ${category}` : ''}</sub>
		<h3><a href={url} target="_blank">{title} ↗</a></h3>
	</div>
	<div class="content">
		<div class="article-type">
			{#each NEWS_TYPE as news_type}
			<label
				class={`radio-button ${news_type.value === 'rm' ? 'rm' : ''}`}
				for={news_type.value + title}
			>
				<input
					id={news_type.value + title}
					type="radio"
					bind:group={type}
					value={news_type.value}
				/>
				<span>{news_type.id}</span>
			</label>
			{/each}
			<label for={`is-ref-${title}`}>
				<input id={`is-ref-${title}`} type="checkbox" bind:checked={typeRef} />
				<span>참고</span>
			</label>
		</div>
		<div class="keyword">
			<input bind:value={keyword1} placeholder="키워드1" autocomplete="on" />
			<input bind:value={keyword2} placeholder="키워드2" autocomplete="on" />
		</div>
	</div>
</div>

<style>
	.header {
		display: flex;
		flex-direction: column;
		padding: 1rem;
	}

	.content {
		padding: 0 1rem 1rem;
	}

	sub {
		margin-bottom: 0.375rem;
		font-size: var(--text-sm);
		color: hsl(var(--muted-foreground))
	}

	h3 {
		font-size: var(--text-md);
	}

	h3 > a {
		color: var(--black);
		text-decoration: none;
	}

	h3 > a:hover {
		text-decoration: underline;
	}

	.article-type {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
	}

	label input[type='radio'] {
		display: none;
	}

	label input[type='radio'] + span {
		display: inline-flex;
		padding: 0.25rem 0.75rem;
		font-size: var(--text-xs);
		font-weight: 600;
		color: hsl(var(--muted-foreground));
		cursor: pointer;
		background-color: transparent;
		border: 1px solid hsl(var(--muted-foreground) / 50%);
	}

	label input[type='checkbox'] + span {
		display: inline-flex;
		padding: 0.25rem 0.75rem;
		font-size: var(--text-xs);
		font-weight: 600;
		color: hsl(var(--blue));
		cursor: pointer;
		user-select: none;
		background-color: transparent;
		border: 1px solid hsl(var(--blue));
	}

	label input[type='checkbox']:checked + span {
		color: hsl(var(--blue-foreground));
		background-color: hsl(var(--blue));
	}

	label input[type='radio']:checked + span {
		color: hsl(var(--primary-foreground));
		background-color: hsl(var(--primary));
		border: 1px solid transparent;
	}

	label.rm input[type='radio'] + span {
		color: hsl(var(--red));
		border: 1px solid hsl(var(--red));
	}

	label.rm input[type='radio']:checked + span {
		color: hsl(var(--red-foreground));
		background-color: hsl(var(--red));
	}

	label input[type='checkbox'] {
		display: none;
	}

	.keyword {
		display: flex;
		flex-wrap: wrap;
		gap: 1rem;
		margin-top: 0.5rem;
	}

	.keyword > input {
		width: 7.5rem;
		height: 1.5rem;
		color: hsl(var(--muted-foreground));
		border: none;
		border-bottom: 1px solid hsl(var(--muted-foreground) / 50%);
		outline: none;
	}
</style>
