// frontend/src/components/base/header.svelte
<header>
	<div class="container">
		<b>News Monitor</b>
	</div>
</header>


<style>
	header {
    width: 100%;
		padding: 0 1.5rem;
		margin: 0 auto;
	}

	.container {
    display: flex;
    align-items: center;
    justify-content: flex-start;
		max-width: 1400px;
		height: 3rem;
		padding: 1rem 0;
	}
</style>

// src/components/base/header.tsx
import { useTheme } from '@/components/theme-provider'
import { Switch } from '@/components/ui/switch'

const Header = () => {
  const { theme, setTheme } = useTheme()

  return (
    <header className="container">
      <div className="flex items-center justify-between py-2 h-12">
        <div className="flex items-center justify-center font-bold">
          News Monitor
        </div>
        <Switch
          checked={theme === 'dark' ? true : false}
          onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
        />
      </div>
    </header>
  )
}

export default Header
